### ISSUE TITLE
daily scrum

### ISSUE THREAD

**Issue by azimatulchamidah** [azimatulchamidah/projek-ppl#35]

**Comment by Zalfaanabilah** [comment]
1. Product owner
- Product Owner memberikan informasi tentang perubahan kebutuhan atau prioritas dari pemilik produk.
- Diskusi mengenai item backlog yang mungkin memerlukan penyesuaian atau klarifikasi.

2. Designer
- Designer memberikan update tentang progres desain.
- Diskusi tentang desain yang belum pas, dan memberikan kesepakatann akhir untuk desain yang diberikan

3. Development
- Setiap anggota tim pengembangan memberikan update singkat tentang pekerjaan yang telah diselesaikan sejak pertemuan sebelumnya.
- Menyampaikan kendala atau hambatan yang dihadapi.
- Diskusi singkat tentang tindakan yang diambil untuk mengatasi hambatan tersebut.

4. Monitoring & Controlling
- Controlling & Monitoring memberikan informasi terkait pengukuran kinerja, metrik proyek, dan pengelolaan risiko.
- Diskusi tentang langkah-langkah untuk memastikan proyek tetap berada pada jalur yang benar.

Pada tahap akhir, dilakukan presentasi mengenai produk yang akan dibuat untuk penguploadan di youtube. setelah penguploadan selesai maka akan dilaksanakan pertemuan terakhir untuk menyelesaikan seluruh Tugas Akhir ini. dan memikirkan apa goal dari produk yang kami buat
