### ISSUE TITLE
bukti kerterlibatan tim

### ISSUE THREAD

**Issue by azimatulchamidah** [azimatulchamidah/projek-ppl#38]

**Comment by Zalfaanabilah** [comment]
berikut adalah bukti keterlibatan tim selama proses pembuatan produk. pembuatan produk dibagi menjadi 4 pertemuan. dimana pertemuan pertama adalah pembahasan yaitu berisi mengenai apa saja yang akan dibuat dan membuat isi dari pertanyaan untuk wawancara. pertemuan kedua yaitu mulai merancang pembuatan dengan bahan seadanya. pertemuan ketiga dengan bahan bahan yang sudah dibeli dan merupakan bahan utama mulai proses pembuatan produk. pertemuan keempat tahap akhir dalam pembuatan produk yaitu membuat finishing produk. 
https://drive.google.com/drive/folders/1afVYt3QcNqNorK-DHnjAcKoNclbMSXqJ?usp=sharing
