### ISSUE TITLE
dokumentasi rekaman wawancara

### ISSUE THREAD

**Issue by azimatulchamidah** [azimatulchamidah/projek-ppl#41]

**Comment by Zalfaanabilah** [comment]
wawancara dilakukan secara random dan mendapatkan 5 orang untuk melakukan tanya jawab sesuai apa yang diinginkan oleh klien
https://drive.google.com/drive/folders/1_XrJLHH_B8ubf85go-lhFGkCGi0TxqXd?usp=sharing

Berikut adalah hasil dokumentasi wawancara
https://drive.google.com/drive/folders/1a1CRkuCEKVyWxXVV7Qan20Ij314XvNaN?usp=sharing
