### ISSUE TITLE
transkrip wawancara

### ISSUE THREAD

**Issue by azimatulchamidah** [azimatulchamidah/projek-ppl#42]

**Comment by Zalfaanabilah** [comment]
Dari hasil wawancara yang didapat, terdapat 5 responden yang memiliki saran dan masukan yang berbeda beda.

Responden 1
responden berperan sebagai penerima diberi pilihan jenis ucapan selamat seperti apa, lalu responden menjawab bucket, bucket yang disesuaikan dengan acara yang akan dihadiri. untuk jenis warna yang diinginkan, responden memilih untuk menyesuaikan. ukuran yang diinginkan sesuai dengan budget yang diinginkan oleh responden. kualitas produk menginginkan kualitas yang terbaik dengan harga yanng telah disepakati

Responden 2
responden berperan sebagai pembeli memilih ucapan selamat dalam bentuk papan ucapan akrilik, dengan detail menggunakan bunga bunga plastik, dengan budget yang telah ditentukan oleh  penjual

Responden 3
responden berperan sebagai penerima memilih ucapan selamat dalam bentuk bucket bunga. responden memilih bunga palsu agar dapat dijadikan sebagai kenangan, dengan tone warna yang ga lebay dan kalem.

Responden 4 
responden berperan sebagai penerima memilih diberi ucapan dalam bentuk bucket snack, dengan pilihan warna yang bebas dan menginginkan kartu ucapan tanpa diberi nama

Responden 5
responden berperan sebagai pembeli yang ingin memberikan bucket bunga sebagai hadiah. dengan budget yang tergantung kedekatan kisaran 35.000-70.000. untuk pemilihan warna tergantung dengan siapa yang dikasih bucket tersebut. bentuk dan bunga dipilih secara random. cara mengetahui pilihan warna, responden langsung menanyakan dan apabila tidak mengetahui warnanya responden memilih warna kalem/pastel. kartu ucapan ditulis sendiri dan dengan ditulis nama pengirim
