### ISSUE TITLE
daftar requirement sebagai hasil analisis

### ISSUE THREAD

**Issue by azimatulchamidah** [azimatulchamidah/projek-ppl#43]

**Comment by azimatulchamidah** [comment]
Berikut  adalah hasil analisis berdasarkan wawancara yang telah dilakukan dengan narasumber mahasiswa yang berada di lingkungan UAD

[requirement analysis.pdf](https://github.com/azimatulchamidah/projek-ppl/files/13849700/requirement.analysis.pdf)

**Comment by Fatim2022** [comment]
Berikut alat dan bahan serta hasil desain secara rinci terkait produk :

[Desain Alat dan Bahan.pdf](https://github.com/azimatulchamidah/projek-ppl/files/13858328/Desain.Alat.dan.Bahan.pdf)


![Desain Buket](https://github.com/azimatulchamidah/projek-ppl/assets/155208725/14dc5c1c-7b92-42d5-b8e6-87dd15e8e2cb)
