### ISSUE TITLE
perhitungan estimasi biaya produksi

### ISSUE THREAD

**Issue by azimatulchamidah** [azimatulchamidah/projek-ppl#49]

**Comment by aryntaridewi** [comment]
Untuk estimasi biaya produksi membuat bucket ini adalah dengan rincian sebagi berikut:
1. Kertas celophen : RP 23.000
2. Kertas krep : RP 37.000
3. Lem tembak : RP 12.000
4. Pita sattin : RP 10.000
5. Tusuk sate : RP 5.000
6. Besi greating card : RP 3.000
7. Plaster : RP 10.000
8. Gabus : RP 7.000
 
JUMLAH KESELURUHAN: RP 107.000
Namun untuk produk jika di jual, kelompok kami memberikan harga sebesar RP 150.000 yang sudah include dengan jasa pembuatan.
