### ISSUE TITLE
perencanaan pengujian produk

### ISSUE THREAD

**Issue by azimatulchamidah** [azimatulchamidah/projek-ppl#51]

**Comment by aryntaridewi** [comment]
Perencanaan pengujian produk dilakukan di lingkungan kampus dengan mengambil 3 orang responden. Di antaranya 2 perempuan dan 1 laki-laki. Pada pengujian produk ini menggunakan wawancara dengan pertanyaan sebagai berikut:
1. Menanyakan pendapat responden mengenai produk
2. Menanyakan apakah dari produk tersebut ada yang harus di benahkan lagi? Jika ada apa yang harus dibenahkan?
3. Ketika para responden telah memberikan pendapat tentang produk, maka selanjutnya menanyakan mengenai produk yang lebih rinci. Mulai dari bentuk, warna yang sudah cocok untuk semua gander.
4. Yang terakhir yaitu mempertanyakan mengenai harga yang cocok untuk produk tersebut.
