### ISSUE TITLE
hasil analisis pengujian produk

### ISSUE THREAD

**Issue by azimatulchamidah** [azimatulchamidah/projek-ppl#53]

**Comment by aryntaridewi** [comment]
Untuk responden pertama memberikan masukan mengenai produk agar menambahkan variasi bunga di dalam bucket, untuk selebihnya responden tidak memberikan komentar yang spesifik.
Responden kedua, memberikan saran jika produk di jual mungkin dapat diberi harga sebesar RP120.000 yang artinya harga tersebut lebih rendah dari harga yang kami tawarkan sebelumnya untuk para responden. Selain itu saran yang diberikan untuk yang lainnya adalah untuk menambahkan warna lainnya dalam bucket karena warna yang kelompok kami gunakan adalah biru tua, biru muda, dan hitam.
Terakhir yaitu responden yang ketiga memberikan saran untuk menaikkan harga bucket dari harga yang kami tawarkan sebelumnya menjadi RP 200.000 atau lebih tinggi dari itu.
